#!/bin/sh

nodesfile=$1
echo > $nodesfile

#                            адрес IP узла
#                            |             разрешение-1/запрет-0 порт1
#                            |             |   адр начало порт1
#                            |             |   |   адр конец порт1
#                            |             |   |   | разрешение-1/запрет-0 порт2
#                            |             |   |   | |   адр начало порт2
#                            |             |   |   | |   |   адр конец порт2
#                            |             |   |   | |   |   |
#sh mslave.cfg.in $nodesfile 192.168.1.128 1 229 230 1   2   5

#sh mslave.cfg.in $nodesfile 192.168.1.128 1 229 230 1   2   5
sh mslave.cfg.in $nodesfile 192.168.1.128 1 129 129 0   2   2
#sh mslave.cfg.in $nodesfile 192.168.100.129 0 229 229 1   1   1

chmod 640 $nodesfile
