#!/bin/sh

nodes=`cat $1`

pthu=/home/utils

ftpfile=ftp.txt
ftplog=ftp.log

for node in $nodes
do
	echo "ascii" > $ftpfile
	echo "cd $pthu" >> $ftpfile
	echo "put wd_$node.lifes wd.lifes" >> $ftpfile
	echo "put master.life" >> $ftpfile
	echo "put mslave.life" >> $ftpfile
	echo "exit" >> $ftpfile
	chmod 640 $ftpfile
	
	ftp $node < $ftpfile > ftplog
	echo "wd.lifes ($node) ... ok"
done
