#!/bin/sh

nodes=`cat $1`

pthm=/home/slave

ftpfile=ftp.txt
ftplog=ftp.log

echo "binary" > $ftpfile
echo "cd $pthm" >> $ftpfile
echo "put mslave" >> $ftpfile
echo "chmod 755 mslave" >> $ftpfile
echo "exit" >> $ftpfile
chmod 640 $ftpfile

for node in $nodes
do
	ftp $node < $ftpfile > ftplog
	echo "mslave ($node) ... ok"
done
