#!/bin/sh

nodes=`cat $1`

pthm=/home/slave

ftpfile=ftp.txt
ftplog=ftp.log

for node in $nodes
do
	echo "ascii" > $ftpfile
	echo "cd $pthm" >> $ftpfile
	echo "put mslave_$node.cfg mslave.cfg" >> $ftpfile
	echo "exit" >> $ftpfile
	chmod 640 $ftpfile
	
	ftp $node < $ftpfile > ftplog
	echo "mslave.cfg ($node) ... ok"
done
